name: Test with KinD

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch history
        run: git fetch --prune --unshallow

      - name: Run chart-testing (lint)
        id: lint
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: lint

      - name: Create kind cluster
        uses: helm/kind-action@v1.0.0
        # Only build a kind cluster if there are chart changes to test.
        if: steps.lint.outputs.changed == 'true'

      - name: Run chart-testing (install)
        if: steps.lint.outputs.changed == 'true'
        uses: helm/chart-testing-action@v1.0.0
        with:
          command: install

      - name: Install chart
        if: steps.lint.outputs.changed == 'true'
        run: |
          kubectl create namespace hello
          helm install hello-kubernetes --namespace hello --generate-name

      - name: List pods
        if: steps.lint.outputs.changed == 'true'
        run: |
          kubectl get pods --all-namespaces
          kubectl get services --all-namespaces

      - name: Port Forward to Service
        if: steps.lint.outputs.changed == 'true'
        run: 'kubectl port-forward -n hello service/hello-service 8081:80 &'

      - name: Test App
        if: steps.lint.outputs.changed == 'true'
        run: |
          curl -s localhost:8081 | grep "I deploy with Helm 3\\\!"
